# Generated by Django 6.0.7 on 2026-08-02 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='servi_par',
            field=models.ForeignKey(blank=True, help_text='Membre du personnel ayant marqué la commande comme servie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_servies', to=settings.AUTH_USER_MODEL),
        ),
    ]
