# Generated by Django 6.0.7 on 2026-08-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_servi_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paye',
            field=models.BooleanField(default=False, help_text='Indépendant du statut de préparation : le client peut payer avant, pendant ou après avoir été servi.'),
        ),
    ]
