# Generated by Django 6.0.7 on 2026-08-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_paye'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='cout_unitaire',
            field=models.PositiveIntegerField(default=0, help_text="Coût d'achat au moment de la commande (historique, pour calcul du bénéfice)"),
        ),
    ]
