# Generated by Django 6.0.7 on 2026-07-31 00:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numéro affiché sur la table (ex: 4)', unique=True)),
                ('code_qr', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique utilisé dans l'URL du QR code", unique=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
