# Generated by Django 6.0.7 on 2026-07-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('biere', 'Bière'), ('soft', 'Boisson sans alcool'), ('plat', 'Plat')], default='biere', max_length=20)),
                ('format', models.CharField(blank=True, help_text='Ex: 33cl, 65cl', max_length=20)),
                ('prix', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('disponible', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='produits/')),
            ],
            options={
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
