# Generated by Django 6.0.7 on 2026-08-02 17:07

import produits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=produits.models._stockage_photos, upload_to='produits/'),
        ),
    ]
