# Generated by Django 6.0.7 on 2026-08-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_produit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('biere', 'Bière'), ('vin', 'Vin'), ('spiritueux', 'Spiritueux'), ('cocktail', 'Cocktail'), ('energisante', 'Boisson énergisante'), ('soft', 'Soft / Sans alcool'), ('plat', 'Plat')], default='biere', max_length=20),
        ),
    ]
