# Generated by Django 6.0.7 on 2026-08-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_finaliser_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='cout',
            field=models.PositiveIntegerField(default=0, help_text="Coût d'achat unitaire en FCFA — sert à calculer le bénéfice dans l'onglet 'Bénéfice' du tableau de bord"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.PositiveIntegerField(help_text='Prix de vente en FCFA'),
        ),
    ]
